name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_project_id: ${{ secrets.PROJECT_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Debug project id
      run: |
        if [ -z "$TF_VAR_project_id" ]; then
          echo "project_id is EMPTY"
          exit 1
        else
          echo "project_id is set"
        fi

    - name: Terraform Init
      run: terraform init

    # - name: Terraform Format Check
    #   run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
